In [8]:


a = np.array([1, 2, 6, 4, 2, 3, 2])
u, indices = np.unique(a, return_inverse=True)
u
indices
u[indices]


array([1, 2, 6, 4, 2, 3, 2])

In [5]:
import numpy as np


In [13]:
a = np.array([1, 2, 6, 4, 2, 3, 2])
u, indices,count = np.unique(a, return_inverse=True,return_counts=True)
u
indices
u[indices]


array([1, 2, 6, 4, 2, 3, 2])

In [14]:
u

array([1, 2, 3, 4, 6])

In [15]:
indices

array([0, 1, 4, 3, 1, 2, 1], dtype=int64)

In [16]:
u[indices]

array([1, 2, 6, 4, 2, 3, 2])

In [17]:
count

array([1, 3, 1, 1, 1], dtype=int64)

In [20]:
for e, i in enumerate(count):
    if ( i != 1 ):
        print(u[e])

2
